apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cica-online-dev
spec:
  selector:
    matchLabels:
      app: cica-online-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: cica-online-dev
    spec:
      containers:
      - name: cica-online-staging
        image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/cica/cicadevelopment:circleci-online-dev2
        ports:
        - containerPort: 6565
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 4010
#          initialDelaySeconds: 15
#          timeoutSeconds: 1
#          periodSeconds: 10


---
kind: Service
apiVersion: v1
metadata:
  name: cica-online-dev-service
  labels:
    app: cica-online-dev-service
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 6565
  selector:
    app: cica-online-dev


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cica-online-dev-ingress
spec:
  rules:
  - host: cica-online-dev.apps.cloud-platform-live-0.k8s.integration.dsd.io
    http:
      paths:
      - path: /
        backend:
          serviceName: cica-online-dev-service
          servicePort: 8080
